# DISMTools (version 0.8) configuration file (TEMPLATE)

[Program]
DismExe="{common:WinDir}\system32\dism.exe"
SaveOnSettingsIni=1

[Personalization]
ColorMode=0
ColorTheme_Light=1
ColorTheme_Dark=0
LanguageCode="en-US"
LogFont="Consolas"
LogFontSi=11
LogFontBold=0
SecondaryProgressPanelStyle=1
AllCaps=0
ExpandedProgressPanel=1
ShowDateAndTime=1

[Logs]
LogFile="{common:WinDir}\Logs\DISM\DISM.log"
LogLevel=3
AutoLogs=1
SystemEditor="{common:WinDir}\system32\notepad.exe"
EnableDynaLog=1

[ImgOps]
Quiet=0
NoRestart=0
NoNTSamMappings=0
PEHelper.UnattendedFile=""
PEHelper.CopyToVentoy=0
PEHelper.Use2023EFI=0
PEHelper.IncludeSysDrvs=1
AppxRemovalDisplayNameFormat=1
PreventSystemFromSleeping=1
HumanizeDates=1

[ScratchDir]
UseScratch=0
AutoScratch=1
ScratchDirLocation=""

[Output]
EnglishOutput=1
ReportView=0

[BgProcesses]
ShowNotification=1
NotifyFrequency=1

[AdvBgProcesses]
EnhancedAppxGetter=1
SkipNonRemovable=1
DetectAllDrivers=0
SkipFrameworks=1
RunAllProcs=0

[Startup]
RemountImages=1
CheckForUpdates=1

[Shutdown]
AutoCleanMounts=0

[WndParams]
WndWidth=1280
WndHeight=720
WndCenter=1
WndLeft=0
WndTop=0
WndMaximized=0

[InfoSaver]
SkipQuestions=1
Pkg_CompleteInfo=1
Feat_CompleteInfo=1
AppX_CompleteInfo=1
Cap_CompleteInfo=1
Drv_CompleteInfo=1

[SearchSettings]
EngineName="DuckDuckGo"
AITolerance=1

[PEPolicy]
ShowWatermark=0
WDSHCGraphoView=1
DTDimShowPnputilOut=1
WDSHCConnAttempts=5
PartTableOverridePreference=0
UEFICA23Preference=0
AutoUnattendCopytoSysprep=0
PXEServerPort=8080
KeyboardLayoutCode="00000409"
KeyboardLayoutOverrideExistingLayout=0
AnswerFileConflictResponse=0