'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("StarterScriptEditor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property account_dev_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_dev_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $env:APIKEY = &quot;YOUR_API_KEY_HERE&quot;
        '''set &quot;API_URI=https://your-service-here.com/API_KEY&quot;.
        '''</summary>
        Friend ReadOnly Property ApiKeyLeakTemplate() As String
            Get
                Return ResourceManager.GetString("ApiKeyLeakTemplate", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property bottomleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottomleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bottomright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottomright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changefont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changefont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classic_pat_params() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classic_pat_params", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colormode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colormode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property example_classic_pat_key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("example_classic_pat_key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property example_finegrained_pat_key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("example_finegrained_pat_key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property finegrained_pat_confirm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finegrained_pat_confirm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property finegrained_pat_params_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finegrained_pat_params_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property finegrained_pat_params_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finegrained_pat_params_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property generate_pat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generate_pat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property generate_token() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generate_token", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property github_account_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("github_account_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property github_devapps_tokens() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("github_devapps_tokens", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inspect_high_severity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspect_high_severity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inspect_low_severity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspect_low_severity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inspect_medium_severity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspect_medium_severity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inspect_security() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspect_security", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newfile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newfile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property openfile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openfile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pin_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pin_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Character Classes:
        '''.        Any character except newline
        '''\d       Digit [0-9]
        '''\D       Non-digit
        '''\w       Word character [A-Za-z0-9_]
        '''\W       Non-word character
        '''\s       Whitespace
        '''\S       Non-whitespace
        '''[abc]    Any of a, b, or c
        '''[^abc]   Not a, b, or c
        '''[a-z]    Lowercase letter
        '''
        '''Quantifiers:
        '''
        '''* 0 or more
        '''- 1 or more
        '''
        '''?        0 or 1
        '''{n}      Exactly n times
        '''{n,}     n or more times
        '''{n,m}    Between n and m times
        '''
        '''Anchors:
        '''^        Start of string/line
        '''$        End of string/line        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RegexCheatsheet() As String
            Get
                Return ResourceManager.GetString("RegexCheatsheet", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property replace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("replace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property savefile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savefile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savefileas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savefileas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property targetversion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("targetversion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property writable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("writable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
