name: Create Nightly Installer

on:
  push:
    branches:
      - dt_pre_*
      - dt_rel*
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'res/**'
  workflow_dispatch:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-runspace:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Set up MSBuild
      uses: microsoft/Setup-MSBuild@v2
    - name: Prepare NuGet packages
      run: .\nugetpkgprep.bat
      continue-on-error: false
    - name: Generate installer
      run: |
        $solutionDir = "$((Get-Location).Path)\"
        $projectDir = "$((Get-Location).Path)\"
        $targetDir = (Get-Location).Path + "\bin\Debug\"
        msbuild Tools\UnpEax\UnpEax.csproj /p:Configuration=Debug /p:DeployOnBuild=true
        msbuild DISMTools.vbproj /p:Configuration=Debug /p:DeployOnBuild=true /p:SolutionDir=$solutionDir /p:ProjectDir=$projectDir /p:TargetDir=$targetDir
        Move-Item -Path "$($solutionDir.TrimEnd("\"))\Installer\Output\dt_setup.exe" -Destination "$($solutionDir.TrimEnd("\"))\Installer\Nightly\dt_setup.exe" -Force
    - name: Push nightly installer
      #uses: stefanzweifel/git-auto-commit-action@v5
      #with:
      #  commit_message: DISMTools Nightly Installer
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          source-directory: '${{ GITHUB_REF_NAME}}'
          destination-github-username: 'CodingWonders'
          destination-repository-name: 'dt-nightly-installers'
          target-branch: main
      if: success()
